### ISSUE TITLE
Add ChaiLove Core

### ISSUE THREAD

**Issue by RobLoach** [kodi-game/game.libretro#32]
[ChaiLove](https://github.com/robloach/chailove) is a game engine for libretro. While I haven't fully tested this, I'd love to have some direction into how to get it working in Retroplayer/KodiGame.

Made the initial Kodi addon work for it over at:
https://github.com/RobLoach/game.libretro.chailove

The beetle-bsnes directory will need a lot of updates:
https://github.com/RobLoach/game.libretro.chailove/tree/master/depends/common/beetle-bsnes

Would love your thoughts on how to get this up and running.

**Comment by garbear** [comment]
Let's move game.libretro.chailove to the kodi-game org. That way, we can add support to our kodi-game-scripting infrastructure here: https://github.com/fetzerch/kodi-game-scripting/blob/master/kodi_game_scripting/config.py. This takes care of most of the details and should generate the depends directory for us.

We need https://github.com/kodi-game/repo-binary-addons/pull/4 (to be updated when game.libretro.chailove is moved)

As for this repo:

* A second sentence in the addon.xml &lt;description> wouldn't hurt
* Icons and (optionally) screenshots should be replaced
* A `buttonmap.xml` and `topology.xml` are needed.  See the long list of examples at the bottom of https://github.com/xbmc/xbmc/pull/13499. The schema is documented [here](https://github.com/kodi-game/game.libretro/blob/master/Schema.md).

**Comment by RobLoach** [comment]
- [x] A second sentence in the addon.xml <description> wouldn't hurt
- [x] Icons and (optionally) screenshots should be replaced
- [ ] A buttonmap.xml and topology.xml are needed

Let's add keyboard/mouse in the PR over at https://github.com/kodi-game/game.libretro.chailove/pull/2
