### ISSUE TITLE
Build broken by removal of struct game_system_av_info and unifying of game streams

### ISSUE THREAD

**Issue by Lou-Cipher** [kodi-game/game.libretro#38]
Recent commit to Garbear's xbmc branch breaks ability to build this addon:

https://github.com/garbear/xbmc/commit/fcb2e1ec31ea40fd00c7f3f31cc4e018f36dd091#diff-7a3216a1f70cc6476dafd600c23fa44c

I have a PR to fix the game_system_av_info issue, but the unified streams break I have yet to fix.
https://github.com/kodi-game/game.libretro/pull/37

**Comment by garbear** [comment]
If you're building my `retroplayer-18alpha1` branch, you'll need to switch to game.libretro branch `streams`. See https://github.com/kodi-game/repo-binary-addons/commit/d566e1d95ee84a543a2412dcd9cea19ba7e6f52f.

**Comment by garbear** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/13976
