### ISSUE TITLE
Compile errors on retroplayer branch

### ISSUE THREAD

**Issue by bh** [kodi-game/game.libretro#45]
For me the current `retroplayer` (5b5a1dd6041f5785be16dad383b614284080a301) branch does not compile. I got the same error as for the Travis build:

https://travis-ci.org/kodi-game/game.libretro/jobs/409429919

**Comment by garbear** [comment]
Try building the `master` branch. `retroplayer` can only be built against my `retroplayer-18beta1` kodi branch. I use this for my test builds.

**Comment by bh** [comment]
Yeah, cool. I tried to build it against xbmc/xbmc@master. Thank you!

**Comment by bh** [comment]
FYI: It now compiles fine on xbmc/xbmc@master! :D
