### ISSUE TITLE
PPA builds failing

### ISSUE THREAD

**Issue by OmniBlade** [kodi-game/game.libretro#92]
Looks like builds for the Ubuntu PPA which is used in preference to the internal kodi addon repos is failing due to unmet dependency on rcheevos. This in turn is making it impossible to install any other libretro addons as they all depend on this. I'm not sure of the best solution as I'm not really familiar with the binary addons build process, but at a glance it looks like if the rcheevos find module fails, it should be built from depends instead rather than the build process bailing.

**Comment by garbear** [comment]
After https://github.com/kodi-game/game.libretro/pull/101 this add-on can now be built with the cmake option `ENABLE_INTERNAL_RCHEEVOS`, which will build rcheevos internally and allow it to be found.
